package studyexpress;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.util.regex.*; 

class StudentEditProfileController
{
    private StudentHomeController back;
    
    private student s;
    private seStudentEditProfileUI studProfile;
    
    StudentEditProfileController(){}
    
    StudentEditProfileController(student s)
    {
        this.s = s;
        studProfile = new seStudentEditProfileUI();
        studProfile.setVisible(true);
        studProfile.setStudent(this.s);
    }
    
    public void backBtnController(student s)
    {
        back = new StudentHomeController(s);
        back.displayStudentInfo();
    }
    
    //pw, fullName, email, phone
    public static void updateProfile(student s, String ... stmts)
    {
        String st = "UPDATE studentid.sinfoafter SET ";
        String newVal = new String();
        for(int i = 0; i < stmts.length; i++)
        {
            if(!stmts[i].isEmpty())
            {
                newVal = stmts[i];
                s.setPassword(i==0?newVal.substring(11):s.getPassword());
                s.setFullName(i==1?newVal.substring(11):s.getFullName());
                s.setEmail(i==2?newVal.substring(8):s.getEmail());
                s.setPhone(i==3?Integer.parseInt(newVal.substring(8)):s.getPhone());
                st += stmts[i] + "'";
                if(i != stmts.length-1 && !stmts[i+1].isEmpty())
                    st += ", ";
            }
        }
        
        st += "WHERE username='" + s.getUsername() +"'";
        //System.out.println("SQL statement " + st);
        
        student.updateAccount(st);
    }
}

public class seStudentEditProfileUI extends javax.swing.JFrame {
    
    private student s;
    private StudentEditProfileController pageLogic = new StudentEditProfileController();

    /**
     * Creates new form seStudentEditProfileUI
     */
    public seStudentEditProfileUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        oldPWLabel = new javax.swing.JLabel();
        fullNameVal = new javax.swing.JTextField();
        newPWLabel = new javax.swing.JLabel();
        emailVal = new javax.swing.JTextField();
        cfmPWLabel = new javax.swing.JLabel();
        phoneVal = new javax.swing.JTextField();
        fullNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        newPwVal = new javax.swing.JPasswordField();
        oldPwVal = new javax.swing.JPasswordField();
        cfmPwVal = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "Student", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        oldPWLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        oldPWLabel.setText("Old Password:");

        newPWLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newPWLabel.setText("New Password:");

        cfmPWLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cfmPWLabel.setText("Confirm Password:");

        fullNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fullNameLabel.setText("Full name:");

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        emailLabel.setText("Email:");

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        phoneLabel.setText("Phone no:");

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit User Details");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jLabel1.setMaximumSize(new java.awt.Dimension(1300, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(1300, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 100));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        saveButton.setText("Save");
        saveButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        newPwVal.setText("jPasswordField1");
        newPwVal.setPreferredSize(new java.awt.Dimension(6, 22));

        oldPwVal.setText("jPasswordField1");
        oldPwVal.setPreferredSize(new java.awt.Dimension(6, 22));

        cfmPwVal.setText("jPasswordField1");
        cfmPwVal.setPreferredSize(new java.awt.Dimension(6, 22));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(phoneLabel)
                            .addGap(35, 35, 35))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fullNameLabel)
                                .addComponent(cfmPWLabel)
                                .addComponent(emailLabel))
                            .addGap(51, 51, 51)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oldPWLabel)
                            .addComponent(newPWLabel))
                        .addGap(51, 51, 51)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneVal, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(fullNameVal)
                    .addComponent(emailVal)
                    .addComponent(newPwVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oldPwVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cfmPwVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(711, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(oldPWLabel)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oldPwVal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPWLabel)
                    .addComponent(newPwVal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cfmPWLabel)
                    .addComponent(cfmPwVal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameLabel)
                    .addComponent(fullNameVal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailVal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneVal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(saveButton))
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String oldPW = oldPwVal.getText(); 
        String newPW = newPwVal.getText();
        String cfmPW = cfmPwVal.getText();
        String fullName = fullNameVal.getText();
        String email = emailVal.getText();
        String phone = phoneVal.getText();
        // prevent empty fields from happening
        if(checkEmptyField(oldPW, newPW, cfmPW, fullName, email, phone))
            JOptionPane.showMessageDialog (null, "All fields are empty!\nNo update is done.");
        else
        {
            //Validate password field
            if(!oldPW.isEmpty() && s.getPassword().equals(oldPW))
            {
                if(!newPW.equals(cfmPW) || oldPW.equals(newPW))
                {
                    JOptionPane.showMessageDialog (null, "Failed to save information:\n"
                                                          + "Either old and new password is the same or new and confirm password does not match");
                }
                else 
                    validateField(fullName, email, phone, cfmPW);
            }
            else if(oldPW.isEmpty() || newPW.isEmpty() || cfmPW.isEmpty())
                validateField(fullName, email, phone, "");
            else
                JOptionPane.showMessageDialog (null, "Old password does not match");
        }
        setFieldsEmpty();
      
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        pageLogic = new StudentEditProfileController ();
        pageLogic.backBtnController(s);
        this.setVisible (false);
    }//GEN-LAST:event_backBtnActionPerformed

    
    public void setUpdate(String pw, String fullName, String email, String phone)
    {
        pw = !pw.isEmpty()?" password='" + pw:"";

        fullName = !fullName.isEmpty()?" fullname='" + fullName:"";

        email = !email.isEmpty()?" email='" + email:"";

        phone = !phone.isEmpty()?" phone='" + phone:"";

        StudentEditProfileController.updateProfile(s, pw, fullName, email, phone);
    }
    
    public void setFieldsEmpty ()
    {
        oldPwVal.setText ("");
        newPwVal.setText ("");
        cfmPwVal.setText ("");
        fullNameVal.setText ("");
        emailVal.setText ("");
        phoneVal.setText ("");
    }
    
    public boolean checkEmptyField(String...fields)
    {
        for(String field:fields)
        {
            if(!field.isEmpty())
                return false;
        }
        return true;
    }
    
    private boolean isName(String fullnameCheck) 
    { 
        
        String regex = "^[a-zA-Z ]+$";
                              
        Pattern pat = Pattern.compile(regex); 
        if (fullnameCheck == null) 
            return false; 
        return pat.matcher(fullnameCheck).matches(); 
    } 
    
    public void validateField(String fullName, String email, String phone, String cfmPW)
    {
        if(!fullName.isEmpty() && !isName(fullName))
            JOptionPane.showMessageDialog (null, "Name can only contain alphabets");
        else if(!email.isEmpty() && !Pattern.matches("^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$", email))
            JOptionPane.showMessageDialog (null, "Invalid email format");
        else if(!phone.isEmpty() && !Pattern.matches("^[89]{1}[0-9]{7}$", phone))
            JOptionPane.showMessageDialog (null, "Invalid phone format, should only contain number");
        else
        {
            setUpdate(cfmPW, fullName, email, phone);
            JOptionPane.showMessageDialog (null, "Updated!");
        }
    }
    
    public void setStudent(student s)
    {
        this.s = s;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seStudentEditProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seStudentEditProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seStudentEditProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seStudentEditProfileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seStudentEditProfileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cfmPWLabel;
    private javax.swing.JPasswordField cfmPwVal;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailVal;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JTextField fullNameVal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newPWLabel;
    private javax.swing.JPasswordField newPwVal;
    private javax.swing.JLabel oldPWLabel;
    private javax.swing.JPasswordField oldPwVal;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneVal;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}

